### PR TITLE
Travis: have a rake for JRuby's sake

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR is trying to allow JRuby 9.1.8.0 to build.

(May need a few tries here in this PR, to get to a green build.)

**Update**: Current failure (even with a `rake` gem installed):

```
bundler: failed to load command: rake (/home/travis/build/dentarg/ruby-2.4-http-timeout-issue/vendor/bundle/jruby/2.3.0/bin/rake)
Gem::Exception: can't find executable rake
```

Hm. 

```
bundler: failed to load command: rspec (/home/travis/build/dentarg/ruby-2.4-http-timeout-issue/vendor/bundle/jruby/2.3.0/bin/rspec)
Gem::Exception: can't find executable rspec
```

**Update**: Changed Bundler configuration in the Gemfile (removed the Gemfile.lock)

### CODE REVIEW

**Comment by dentarg** [comment]
👍

**Comment by dentarg** [comment]
can it be the `sed` trickery that mess things up for jruby? https://github.com/dentarg/ruby-2.4-http-timeout-issue/blob/ec1e958f1daf89bb15b122d99133f136e630dd91/.travis.yml#L20

**Comment by olleolleolle** [comment]
Ah, I know: 

- `git rm Gemfile.lock`
- in `Gemfile`: use `ruby RUBY_VERSION` instead

I'll do it in this branch

**Comment by olleolleolle** [comment]
@dentarg There!

**Comment by dentarg** [comment]
Thanks @olleolleolle :)

**Pull request merged**
